---
title: "Honey Bees - DESeq"
author: Lindsay Rutter
output:
  packagedocs::package_docs:
    toc: true
    toc_collapse: true
vignette: >
  %\VignetteEngine{packagedocs::redirect}
---

<meta http-equiv="content-type" content="text/html;charset=utf-8" />

```{r global_options, include=FALSE}
# R output pre blocks are styled by default to indicate output
knitr::opts_chunk$set(
  comment = NA,
  cache = TRUE,
  fig.height = 8,
  fig.width = 10
)
```

```{r}
library(DESeq2)
library(gplots)
library(RColorBrewer)
library(data.table)
library(ggplot2)

thisPath <- getwd()

data <- readRDS("../../data/data.Rds")
data <- as.matrix(data)

coldata = data.frame(row.names = colnames(data), virus = unlist(lapply(colnames(data), function (x) substring(unlist(strsplit(x, "[.]"))[1],1,1))), diet = unlist(lapply(colnames(data), function (x) substring(unlist(strsplit(x, "[.]"))[1],2,2))), treatment = unlist(lapply(colnames(data), function (x) unlist(strsplit(x, "[.]"))[1])))

dds = DESeqDataSetFromMatrix(countData = data, colData = coldata, design = ~ virus + diet)
dds <- DESeq(dds)
```

```{r}
dataMetrics <- list()

res <- results(dds, contrast=c("virus","N","V"))
hist(res$pvalue, breaks=20, col="grey", main=paste("pvalue for N and V"))

allPairs = data.frame(Treatment1 = factor(), Treatment2 = factor(), NumberDEG = numeric())
degLength <- length(which((res@listData)$padj <0.05))
allPairs = rbind(allPairs, data.frame(Treatment1 = "N", Treatment2 = "V", NumberDEG = degLength))

metrics = as.data.frame(res@listData)
metrics = cbind(ID = res@rownames, metrics)
metrics$ID = as.character(metrics$ID)
dataMetrics[["N_V"]] <- metrics
```

```{r}
res <- results(dds, contrast=c("diet","C","R"))
hist(res$pvalue, breaks=20, col="grey", main=paste("pvalue for C and R"))

degLength <- length(which((res@listData)$padj <0.05))
allPairs = rbind(allPairs, data.frame(Treatment1 = "C", Treatment2 = "R", NumberDEG = degLength))

metrics = as.data.frame(res@listData)
metrics = cbind(ID = res@rownames, metrics)
metrics$ID = as.character(metrics$ID)
dataMetrics[["C_R"]] <- metrics
allPairs
saveRDS(dataMetrics, file="dataMetrics.Rds")
```


```{r}
plotDispEsts(dds, ylim = c(1e-6, 1e1))
```

Taking rlog transformation for EDA.

```{r}
rld <- rlog(dds)
rldDF <- as.data.frame(assay(rld))
saveRDS(rldDF, file="dataRLD.Rds")
```

```{r}
sampleDists <- dist(t(assay(rld)))
sampleDistMatrix <- as.matrix(sampleDists)
rownames(sampleDistMatrix) <- paste(rld$treatment, rld$patient, sep="-")
colnames(sampleDistMatrix) <- NULL
colours = colorRampPalette(rev(brewer.pal(9, "Blues")))(255)
heatmap.2(sampleDistMatrix, trace="none", col=colours)
```

```{r}
print(plotPCA(rld, intgroup="treatment") + geom_label(aes(label = name), label.size=0.001))
```
